
-- Insert common stores if they don't exist
INSERT INTO stores (name, slug, is_verified) VALUES
('Amazon', 'amazon', true),
('Mercado Libre', 'mercado-libre', true),
('Sears', 'sears', true),
('Liverpool', 'liverpool', true),
('Miniso', 'miniso', true),
('Walmart', 'walmart', true),
('Coppel', 'coppel', true),
('Palacio de Hierro', 'palacio-de-hierro', true),
('Sam''s Club', 'sams-club', true),
('Costco', 'costco', true),
('AliExpress', 'aliexpress', true),
('Temu', 'temu', true),
('Shein', 'shein', true),
('Nike', 'nike', true),
('Adidas', 'adidas', true),
('Zara', 'zara', true),
('H&M', 'hm', true),
('Bershka', 'bershka', true),
('Pull&Bear', 'pull-and-bear', true),
('Oxxo', 'oxxo', true),
('7-Eleven', '7-eleven', true),
('Farmacias Guadalajara', 'farmacias-guadalajara', true),
('Farmacias del Ahorro', 'farmacias-del-ahorro', true),
('Soriana', 'soriana', true),
('Chedraui', 'chedraui', true),
('Bodega Aurrera', 'bodega-aurrera', true),
('Elektra', 'elektra', true),
('Sanborns', 'sanborns', true),
('Mixup', 'mixup', true),
('GamePlanet', 'gameplanet', true),
('Sony', 'sony', true),
('Samsung', 'samsung', true),
('Apple', 'apple', true),
('Microsoft', 'microsoft', true),
('Steam', 'steam', true),
('PlayStation', 'playstation', true),
('Xbox', 'xbox', true),
('Nintendo', 'nintendo', true),
('Epic Games', 'epic-games', true),
('Ubisoft', 'ubisoft', true),
('GOG', 'gog', true),
('Humble Bundle', 'humble-bundle', true),
('Green Man Gaming', 'green-man-gaming', true),
('Eneba', 'eneba', true),
('CDKeys', 'cdkeys', true),
('Instant Gaming', 'instant-gaming', true),
('Kinguin', 'kinguin', true),
('G2A', 'g2a', true)
ON CONFLICT (slug) DO NOTHING;
